function objetos = crear_objetos_ejemplo()
% Crea objetos de cielo profundo de ejemplo basados en tu CSV
  
  objetos = [
    struct('catalogo', 'M42', 'nombre', 'Gran Nebulosa de Orión', 'constelacion', 'Orion', ...
           'tipo', 'Nebulosa de Emisión', 'ascension_recta', 5.5883, 'declinacion', -5.4500, ...
           'magnitud', 4.0, 'tamano', 65, 'descripcion', 'Región de formación estelar visible a simple vista'),
    
    struct('catalogo', 'M31', 'nombre', 'Galaxia de Andrómeda', 'constelacion', 'Andromeda', ...
           'tipo', 'Galaxia Espiral', 'ascension_recta', 0.7129, 'declinacion', 41.2692, ...
           'magnitud', 3.4, 'tamano', 190, 'descripcion', 'Galaxia espiral más cercana, visible a simple vista'),
    
    struct('catalogo', 'M13', 'nombre', 'Gran Cúmulo de Hércules', 'constelacion', 'Hercules', ...
           'tipo', 'Cúmulo Globular', 'ascension_recta', 16.6915, 'declinacion', 36.4617, ...
           'magnitud', 5.8, 'tamano', 20, 'descripcion', 'Uno de los cúmulos globulares más brillantes del norte')
  ];
  
endfunction