function dibujar_referencias_muy_anchas()
  % DIBUJAR_REFERENCIAS_MUY_ANCHAS - Optimizado para visualización ancha

  ax = gca;
  
  % Elementos PRINCIPALES para leyenda
  h1 = plot(ax, [0, 24], [0, 0], 'k-', 'LineWidth', 2.5, ...
            'DisplayName', 'Ecuador Celeste');
  
  % Agrupar trópicos en una sola entrada de leyenda
  h2 = plot(ax, [0, 24], [23.5, 23.5], '--', 'Color', [0.8, 0.4, 0], ...
            'LineWidth', 1.5, 'DisplayName', 'Trópicos');
  plot(ax, [0, 24], [-23.5, -23.5], '--', 'Color', [0.8, 0.4, 0], ...
       'LineWidth', 1.5, 'HandleVisibility', 'off');
  
  % Agrupar círculos polares en una sola entrada
  h3 = plot(ax, [0, 24], [66.5, 66.5], '--', 'Color', [0.4, 0.4, 0.8], ...
            'LineWidth', 1.5, 'DisplayName', 'Círculos Polares');
  plot(ax, [0, 24], [-66.5, -66.5], '--', 'Color', [0.4, 0.4, 0.8], ...
       'LineWidth', 1.5, 'HandleVisibility', 'off');
       
  % Líneas de declinación cada 30°
  for dec = [-60, -30, 30, 60]
    plot(ax, [0, 24], [dec, dec], '--', 'Color', [0.7, 0.7, 0.7], ...
         'LineWidth', 0.5, 'HandleVisibility', 'off');
  endfor
  
  % Líneas de AR cada 1 hora (más densas para visualización ancha)
  for ar = 1:23
    plot(ax, [ar, ar], [-90, 90], ':', 'Color', [0.9, 0.9, 0.9], ...
         'LineWidth', 0.3, 'HandleVisibility', 'off');
  endfor
  
  % Puntos cardinales con texto MÁS GRANDE
  text(ax, 6, 85, 'NORTE', 'HorizontalAlignment', 'center', ...
       'FontSize', 14, 'FontWeight', 'bold', 'BackgroundColor', 'white', ...
       'EdgeColor', 'black', 'Margin', 2);
  text(ax, 6, -85, 'SUR', 'HorizontalAlignment', 'center', ...
       'FontSize', 14, 'FontWeight', 'bold', 'BackgroundColor', 'white', ...
       'EdgeColor', 'black', 'Margin', 2);
  text(ax, 23, 0, 'ESTE', 'HorizontalAlignment', 'center', ...
       'FontSize', 12, 'FontWeight', 'bold', 'BackgroundColor', 'white', ...
       'EdgeColor', 'black', 'Margin', 1);
  text(ax, 1, 0, 'OESTE', 'HorizontalAlignment', 'center', ...
       'FontSize', 12, 'FontWeight', 'bold', 'BackgroundColor', 'white', ...
       'EdgeColor', 'black', 'Margin', 1);
endfunction