function objetos = obtener_objetos_profundos()
% OBTENER_OBJETOS_PROFUNDOS Carga objetos de cielo profundo

  persistent objetos_cache;
  
  if isempty(objetos_cache)
    % Intentar cargar desde archivo
    archivo = 'datos/objetos_profundos.csv';
    if exist(archivo, 'file')
      objetos_cache = leer_csv_objetos(archivo);
    else
      % Datos básicos en memoria
      objetos_cache = struct(...
        'catalogo', {'M42', 'M45', 'M31', 'M13', 'M57'}, ...
        'nombre', {'Gran Nebulosa de Orión', 'Pléyades', 'Galaxia de Andrómeda', ...
                  'Cúmulo de Hércules', 'Nebulosa del Anillo'}, ...
        'constelacion', {'Orion', 'Taurus', 'Andromeda', 'Hercules', 'Lyra'}, ...
        'tipo', {'Nebulosa', 'Cúmulo', 'Galaxia', 'Cúmulo', 'Nebulosa'}, ...
        'ra', {5.5883, 3.7917, 0.7129, 16.6915, 18.8850}, ...
        'dec', {-5.4500, 24.1050, 41.2692, 36.4617, 33.0289}, ...
        'magnitud', {4.0, 1.6, 3.4, 5.8, 8.8}, ...
        'tamano', {65, 110, 190, 20, 1});
    endif
  endif
  
  objetos = objetos_cache;
endfunction